[tool.black]
line-length = 88
target-version = ['py39', 'py310', 'py311']

[tool.ruff]
line-length = 88
select = ["E", "W", "F", "C", "B"]
ignore = ["E501"]

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -q --strict-markers --cov=bot --cov-report=term-missing"
testpaths = [
    "tests",
]
python_files = "test_*.py"
asyncio_mode = "auto"
