name: Continuous Deployment

on:
  push:
    branches:
      - main
      - test
      - dev

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy-dev:
    name: Deploy to Development
    if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Dev Environment
        run: |
          echo "🚀 Deploying to Development Environment..."
          echo "Environment: Development"
          echo "Branch: dev"
          echo "Commit: ${{ github.sha }}"
          # Add actual deployment logic here
          # Example: Docker build and deploy to development server

  deploy-test:
    name: Deploy to Test/Staging
    if: github.ref == 'refs/heads/test' && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Staging Environment
        run: |
          echo "🚀 Deploying to Staging Environment..."
          echo "Environment: Staging"
          echo "Branch: test"
          echo "Commit: ${{ github.sha }}"
          # Add actual deployment logic here

  deploy-production:
    name: Deploy to Production
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: production
    needs: [lint-and-security-check]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Deploy to Production
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        run: |
          echo "🚀 Deploying to Production Environment..."
          echo "Environment: Production"
          echo "Branch: main"
          echo "Commit: ${{ github.sha }}"
          echo "Docker Image: ${{ steps.meta.outputs.tags }}"
          # Add actual production deployment logic here
          # Example: Update Kubernetes deployment, restart systemd service, etc.

  lint-and-security-check:
    name: Final Security Check
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety

      - name: Run Bandit security check
        run: bandit -r bot/ -f json -o bandit-report.json

      - name: Run Safety dependency check
        run: safety check --json --output safety-report.json

      - name: Upload security reports
        uses: actions/upload-artifact@v3
        with:
          name: security-reports
          path: |
            bandit-report.json
            safety-report.json
